### PR TITLE
Simplify CMake scripts and follow modern conventions

### PR DESCRIPTION
**Pull request by drbild**
This patch series rewrites the CMake build scripts for AMCL to both simplify
and shorten them and to follow common conventions that will make usage
of AMCL by downstream projects much easier.  It also fixes several minor bugs in the examples and test code that were identified during the rewrite.

First, the prior build scripts were extremely verbose.  The AMCL curve
and RSA parameters were repeated in the CMakeLists.txt in each
subdirectory.  The "string(REPLACE ...)" and "configure_file(...)"
commands to expand a template source file with these parameters were
repeated for every single template file.  This repetition was both
error prone when adding new curves and obscured the interesting
details in the various build scripts.

Secondly, the scripts did not build the project in a modern,
"standard" way.  For example: Install paths were hardcoded, rather
than using the GNUInstallDirs module, breaking installation on
multi-arch systems. Unnecessary properties were set when the default
would suffice, e.g., install file permissions. Built libraries were
copied around the build tree to let the Python tests execute, rather
than simply setting the LD_LIBRARY_PATH (or equivalent) environment
variable for the test. CMake *config.cmake and pkgconfig *.pc files
were not exported to simplify importing by downstream users. And more.

Fixing these issues one pull request at a time isn't feasible, so this
commit modernizes the CMake usage in one go:

* ACML curve and RSA parameters are defined in one location,
  cmake/AMCLParameters.cmake

* Functions for expanding template files given a curve name or RSA
  level are defined in one location, cmake/AMCLExpand.cmake

* Templated source files are differentiated from actual source files
  in the standard fasion, a '.in' suffix. E.g., *.c.in or *.h.in.

* Expanded template files are placed in the build directory, but
  complete source files are not needlessly copied to the build
  directory.

* All supported RSA levels and curves are built by default. This
  simplifies packaging for distributions. The AMCL_RSA and AMCL_CURVE
  options can be set to override that default.

* The WORD_SIZE (aka AMCL_CHUNK) is automatically detected when
  possible (see cmake/DetermineWordSize.cmake). The user may still
  manually specify if desired.

* The de facto standard BUILD_DOCS and BUILD_TESTING options are used
  to conditionally compile the docs and tests.

* Install locations are determined using the standard GNUInstallDirs
  module. This allows packaging for easy packaging for variety of
  systems, including all standard Linux distributions.

* Versions and SO versions are set on library targets so that CMake
  will generate and install the appropriate versioned symlinks.

* A *Config.cmake script is exported so that downstream CMake projects
  can simply call `find_package(AMCL)` to use the library. E.g., the
  libamcl_rsa_2048 can be used by simply calling
  `target_link_libraries(myprog AMCL::rsa_2048)`.

* A pkg-config *.pc file is exported so that downstream autotools
  projects can easily find the library.

* The CPack configuration is moved to CPackConfig.cmake to not clutter
  up the main build logic.

The remainder of this patch series fixes a variety of small bugs in
the examples, test scripts, and build process that were uncovered as
part of this rewrite.

### CODE REVIEW

**Comment by drbild** [comment]
Looks like I need to either update the `mingw` configs in the Makefile to specify a `WORD_SIZE` or update the DetectWordSize to support the `mingw` compilers.  

The Makefile still has a bunch of `AMCL_CHUNK=` lines that should be updated to `WORD_SIZE=`. Or the CMake should be changed to accept either name.

**Comment by drbild** [comment]
These build scripts now handle all of the cross-compilation oddities (at least as well as the previous version did), but the CI fails because the log output exceeds the 4 MB limit imposed by Travis.  

A reorganization of the Makefile `qa` target is probably the correct way to fix this.  Reducing the total output (by say not running `make doc` on every target) is another option.

Any thoughts @kealan ?

**Comment by drbild** [comment]
(Right now, the tip of this branch replaces the `qa` target with one full build --- all supported curves and RSA levels -- per architecture.  This too is killed by Travis because it doesn't output anything for over 10 minutes when doing the ASAN tests.  The Docker/Makefile combo appears to buffer output during one build, so Travis doesn't see any activity until that whole build & test is complete.  This too could probably be rectified.)

**Comment by kealan** [comment]
Hi David Thanks for this substantial contribution. I have just made a PR to remove "make doc" from all the builds. When it is merged could you please re-base and bump the VERSION file?

What is your view on the way the code is built? We seemed to arrived at a very complicated build system unlike anything I have seen in other projects! We could remove the Makefile and just have a shell script for building the library for test. 

Also, I am not sure what is the advantage of docker is at least for testing. It would useful to have a Dockerfile to build the library using the default configuration as defined in cmake.

**Comment by drbild** [comment]
Thanks for the `Makefile` changes.  The Travis builds completed fine this time.

I've bumped the version to `4.7.0`.

I think simplifying the Makefile/test script/Docker stuff makes.   If I get some time, I'll open an issue to discuss possible approaches.

The docker file did simplify testing the cross-compiled variants.  I didn't have to install wine, mingw-64, etc. locally.  (Although I did eventually anyway, because running through Docker was much slower on my Mac.)

**Comment by drbild** [comment]
@kealan hold off on merging this.  My hack in `AMCLConfig.cmake.in` to build up the list of `ACML_LIBRARIES` (overriding `add_library`) isn't safe.

CMake segfaults if `find_package(AMCL)` is executed more than once (say by two dependencies independently).

I'll rewrite that at update this branch.

**Comment by drbild** [comment]
@kealan Fixed the hack in `AMCLCOnfig.cmake.in`, so this should be ready for review/merge once Travis completes.

**Comment by drbild** [comment]
@kealan Any chance you can look at this in the next few days?

**Comment by kealan** [comment]
Sorry David for the delay but we got sidelined with another project. We had a good look at this for the last couple of days and it is a really great improvement.

**Pull request merged**
